name: Auto Rebase Pull Request

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rebase and create pull request
        run: |
          git config user.name tanujsharan
          git config user.email tanujsharan22@gmail.com
          git checkout main
          git pull
          git checkout dev
          git rebase main
          git push --force-with-lease origin dev
          gh pr create --base main --head dev --title "Auto Rebase Pull Request"
